# render.yaml
# See https://render.com/docs/blueprint-spec for details
services:
  - type: web
    name: amar-abracar-site
    env: docker
    repo: https://github.com/fell-z/amar-abracar-site.git
    plan: free
    healthCheckPath: /
    envVars:
      - key: RUBY_VERSION
        value: "4.0.2"
      - key: DATABASE_URL
        fromDatabase:
          name: amar-abracar-site
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
      - key: DEFAULT_ADMIN_EMAIL
        sync: false
      - key: DEFAULT_ADMIN_PASS
        sync: false

databases:
  - name: amar-abracar-site
    plan: free
    postgresMajorVersion: 18
    ipAllowList: []
